config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "sessions#show"
  get '/presignup' => 'sessions#accounttype', as: :presignup

  get '/existingsignup' => 'sessions#choosefamily', as: :choosefamily
  post '/existingsignup' => 'sessions#choosemember'
  post "/editaccount" => 'sessions#edit', as: :editaccount
  patch '/updateaccount' => 'sessions#update'

  get '/edit' => 'sessions#editselfaccount', as: :edit
  post '/edit' => 'sessions#validatesself'

  get '/signup' => 'sessions#newaccount', as: :signup
  post '/signup' => 'sessions#createaccount'

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  resources :sessions, only: [:edit, :update]
  resources :memories
  resources :people
  resources :families


end

app/models/person.rb
class Person < ApplicationRecord
  has_attached_file :image, styles: {large: "600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :family
  has_many :tags, dependent: :delete_all
  has_many :memories, through: :tags, dependent: :delete_all
  has_secure_password

  validates :username, presence: true, uniqueness: true, :if => :username
  validates :password, presence: true, :if => :password
  validates :dob, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authorize
  def index
    @people = current_user.family.people.sort_by{|person| person.dob.strftime("%Y%m%d").to_i}
    @family = current_user.family
  end

  def new
    @person = Person.new()
  end

  def create
     @person = Person.new(person_params)
     @person.family_id = current_user.family.id
     @person.username = "#{@person.full_name} #{@person.dob}"
     @person.password = "password"
     if @person.valid?
       @person.save
       redirect_to @person
     else
       flash[:errors] = @person.errors.full_messages
       redirect_to new_person_path
     end
   end

  def show
    if Person.find_by_id(params[:id])
      @person = Person.find(params[:id])
    else
      render "people/_noaccess.html.erb"
    end
  end

  def edit
    if Person.find_by_id(params[:id])
      @person = Person.find(params[:id])
    else
      render "people/_noaccess.html.erb"
    end
  end

  def update
  @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to person_path(@person)
    else
      flash[:errors] = @person.errors.full_messages
      redirect_to edit_person_path(@person)
    end
  end

  def destroy
   @person = Person.destroy(params[:id])
   redirect_to people_path
  end

  private

  def person_params
    params.require(:person).permit(:first_name, :last_name, :bio, :dob, :dod, :image)
  end
end

app/views/people/_form.html.erb
<% if flash[:errors] %>
  <ul>
    <br/>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %><br/>

<%= form_for @person, html: { multipart: true } do |f| %>
  <%= f.label :first_name %><br/>
  <%= f.text_field :first_name %><br/>
  <%= f.label :last_name %><br/>
  <%= f.text_field :last_name %><br/>
  <%= f.label :bio %><br/>
  <%= f.text_field :bio %><br/>
  <%= f.label :date_of_birth %><br/>
  <%= f.date_field :dob %><br/>
  <%= f.label :date_of_death %><br/>
  <%= f.date_field :dod %><br/>
  <%= f.label :picture %><br/>
  <%= f.file_field :image %><br/>
  <% if @person == current_user %>
    <%= f.submit "Update Account" %>
  <% else %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/people/edit.html.erb
<% if !current_user.family.people.include?(@person) %>
  <%= render 'noaccess' %>
<% else %>
  <h2> Edit <%= @person.full_name %> </h2>
  <%= render 'form' %>
  <br/>
  <%= form_tag person_path(@person), method: 'delete' do %>
  <% if @person == current_user %>
    <%= submit_tag('Delete Account') %>
  <% else %>
    <%= submit_tag('Delete Person') %>
  <% end %>
  <% end %>
<% end %>

app/views/people/index.html.erb
<br/>
<br/>
<h2> The <%= @family.family_name %> Family Tree </h2>
<h3>  <%= @family.family_info %> </h3>

<% @people.each do |person| %>
  <ul>
    <li> <%=  link_to person.first_name, person%></li>
  </ul>

<% end %>
<br/>
<%= link_to "Edit Family", edit_family_path(current_user.family)  %>

app/views/people/new.html.erb
<h2> Add New Family Member </h2>
<%= render 'form' %>

app/views/people/show.html.erb
<% if !current_user.family.people.include?(@person) %>
  <%= render 'noaccess.html.erb' %>
<% else %>
  <h2> <%=  @person.first_name %> <%= @person.last_name %></h2>
  <img src=" <%= @person.image_url %> " alt=""> <br/>

  <% if @person.image.url != "/images/original/missing.png" %>
    <%= image_tag @person.image.url(:medium) %> <br/>
  <% end %>

    <ul>
      <label>Biography: </label>  <%= @person.bio %></br></br>
      <label>Date of Birth: </label>  <%= @person.dob %></br></br>
      <% if @person.dod %>
        <label>Date of Death: </label>  <%= @person.dod %></br></br>
      <% end  %>
    </ul>

    <% if @person.memories.any? %>
      <h1>Memories</h1>
    <ul>
      <% @person.memories.each do |memory| %>
        <% if memory.image.url != "/images/original/missing.png" %>
          <li><%= link_to image_tag(memory.image.url(:thumb)), memory %></li>
        <% end %>

      <% end %>
    <% end %>
  </ul>
    </br></br></br></br>
  <% if !@person.is_account %>
    <%= link_to("Edit Person", edit_person_path )%></br></br>
    <%= link_to("All People", people_path) %></br></br>
  <% end %>
<% end %>