config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "sessions#show"
  get '/presignup' => 'sessions#accounttype', as: :presignup

  get '/existingsignup' => 'sessions#choosefamily', as: :choosefamily
  post '/existingsignup' => 'sessions#choosemember'
  post "/editaccount" => 'sessions#edit', as: :editaccount
  patch '/updateaccount' => 'sessions#update'

  get '/edit' => 'sessions#editselfaccount', as: :edit
  post '/edit' => 'sessions#validatesself'

  get '/signup' => 'sessions#newaccount', as: :signup
  post '/signup' => 'sessions#createaccount'

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  resources :sessions, only: [:edit, :update]
  resources :memories
  resources :people
  resources :families


end

app/models/memory.rb
class Memory < ApplicationRecord
  has_attached_file :image, styles: {large: "600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :family
  has_many :tags, dependent: :delete_all
  has_many :people, through: :tags
  validates :title, presence: true

  #create a new tag instance
  def create_tag(person_id)
    Tag.create(person_id: person_id, memory_id: self.id)
  end

  #returns an array of people that are tagged to this memory
  def get_tagged_people
    tagged_people = []
    Tag.where(memory_id: self.id).each do |tag|
      tagged_people << Person.find(tag.person_id)
    end

    tagged_people
  end

end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :authorize

  def index
    @family = current_user.family
    @memories = current_user.family.memories
  end

  def new
    @memory = Memory.new()
    @people = current_user.family.people
  end

  def create
    @memory = Memory.new(memory_params)
    @memory.family_id = current_user.family.id
    if @memory.valid?
      @memory.save
      params[:memory][:person_ids].each do |id|
        @memory.create_tag(id)
      end
      redirect_to @memory
    else
      flash[:errors] = @memory.errors.full_messages
      redirect_to new_memory_path
    end
  end

  def show
    if Memory.find_by_id(params[:id])
      @memory = Memory.find(params[:id])
      @tagged_people = @memory.get_tagged_people
    else
      render "memories/_noaccess.html.erb"
    end

  end

  def edit
    if Memory.find_by_id(params[:id])
      @memory = Memory.find(params[:id])
      @people = current_user.family.people
    else
      render "memories/_noaccess.html.erb"
    end
  end

  def update
    @memory = Memory.find(params[:id])
    @memory.update(memory_params)
    if @memory.valid?
      redirect_to @memory
      @memory.tags.each do |tag|
        tag.destroy
      end
      params[:memory][:person_ids].each do |id|
        @memory.create_tag(id)
      end
    else
      flash[:errors] = @memory.errors.full_messages
      redirect_to edit_memory_path
    end
  end

  def destroy
    Memory.destroy(params[:id])
    redirect_to memories_path
  end

  private

  def memory_params
    params.require(:memory).permit(:title, :description, :image_url, :image)
  end

end

app/views/memories/_form.html.erb
<% if flash[:errors] %>
  <ul>
    <br/>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %><br/>

<%= form_for @memory, html: { multipart: true } do |f| %>
  <%= f.label :title %><br/>
  <%= f.text_field :title %><br/>
  <%= f.label :description %><br/>
  <%= f.text_field :description %><br/>
  <%= f.label :image %><br/>
  <%= f.file_field :image %><br/>
  <%= f.collection_check_boxes(:person_ids, @people, :id, :full_name) %><br/>
  <%= f.submit %>
<% end %>

app/views/memories/edit.html.erb
<% if !current_user.family.memories.include?(@memory) %>
  <%= render 'noaccess' %>
<% else %>
  <h2>Edit Memory</h2><br/>

  <%= render 'form' %><br/>
  <%= form_tag memory_path(@memory), method: 'delete' do %>
   <%= submit_tag 'Delete Memory'%>
  <% end %>
<% end %>

app/views/memories/index.html.erb
<h2> <%= @family.family_name %> Memories </h2>

<% @memories.each do |memory| %>
  <ul>
    <li> <%= link_to(memory.title, memory) %></li>
  </ul>
<% end %>

app/views/memories/new.html.erb
<h2>Create a New Memory</h2><br/>

<%= render 'form' %>

app/views/memories/show.html.erb
<% if !current_user.family.memories.include?(@memory) %>
  <%= render 'noaccess' %>
<% else %>
  <h2><%= @memory.title %></h2>

  <img src= "<%= @memory.image_url %>"/><br/>
  <% if @memory.image.url != "/images/original/missing.png" %>
    <%= image_tag @memory.image.url(:medium) %><br/>
  <% end %>

  Description: <br/>
  <%=  @memory.description %> <br/><br/>

  Tagged People: <br/>
  <% @tagged_people.each do |p| %>
    <ul>
      <li><%= link_to p.full_name, p %></li>
    </ul>
  <% end %>
  <br/>

  <%= link_to("Edit Memory", edit_memory_path )%><br/>
  <%= link_to("All Memories", memories_path) %><br/>
<% end %>